version: '3'
services:
  anvil:
    image: ghcr.io/ensdomains/anvil:latest
    ports:
      - '8545:8545'
    entrypoint: /bin/sh -c 'anvil --chain-id 1337 --gas-limit 50000000 --timestamp $BLOCK_TIMESTAMP $ANVIL_EXTRA_ARGS'
    environment:
      ANVIL_IP_ADDR: '0.0.0.0'
  graph-node:
    image: graphprotocol/graph-node:v0.27.0
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
      - anvil
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'mainnet:http://anvil:8545'
      GRAPH_LOG: $GRAPH_LOG_LEVEL
      GRAPH_ALLOW_NON_DETERMINISTIC_IPFS: 'true'
      GRAPH_ETHEREUM_CLEANUP_BLOCKS: 'true'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  ipfs:
    image: ipfs/go-ipfs:v0.4.23
    ports:
      - '5001:5001'
    volumes:
      - $DATA_FOLDER/ipfs:/data/ipfs
  postgres:
    image: postgres:14
    ports:
      - '5432:5432'
    command: ['postgres', '-cshared_preload_libraries=pg_stat_statements']
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
    volumes:
      - $DATA_FOLDER/postgres:/var/lib/postgresql/data
  metadata:
    image: ghcr.io/ensdomains/ens-metadata-service:latest
    depends_on:
      - anvil
      - graph-node
    ports:
      - '8080:8080'
    environment:
      - ADDRESS_ETH_REGISTRAR=$ADDRESS_ETH_REGISTRAR
      - ADDRESS_NAME_WRAPPER=$ADDRESS_NAME_WRAPPER
      - RPC_PROVIDER=http://anvil:8545
      - SUBGRAPH_URL=http://graph-node:8000/subgraphs/name/graphprotocol/ens